info:
  app:
    description: Inbound base repo for MAWM Interface development
    name: Inbound
    version: ${project.version}
logging:
  level:
    ROOT: INFO
    org:
      springframework:
        integration: INFO
mif:
  isEnabled: true
  host:
  password:
  username:
sftp:
  inbound-po:
    host: 127.0.0.1
    port: 2222
    username: foo
    password: pass
  inbound-mms_asn:
    host: 127.0.0.1
    port: 2222
    username: foo
    password: pass
  inbound-br_asn:
    host: 159.65.145.21
    port: 22
    username: lchintala
    password: W@ter@2023
  outbound:
    host: 127.0.0.1
    port: 2222
    username: foo
    password: pass

activemq:
  inbound:
    broker-url:
    password:
    username:

spring:
  application:
    name: Inbound
  jms:
    servicebus:
      enabled: false
  cloud:
    gcp:
      core:
        enabled: false
      pubsub:
        enabled: false

#  quartz:
#    job:
#      initialize-on-prop: true
#
#    enabled: true
#    schema-initialize: true
#    auto-startup: true
#    scheduler-name: ItemInboundScheduler
#    job-store-type: jdbc
#    overwrite-existing-jobs: true
#    properties.org.quartz:
#      jobStore:
#        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#        isClustered: true
#        clusterCheckinInterval: 2000
#        tablePrefix: QRTZ_
#        misfireThreshold: 500
#        useProperties: true
#      scheduler:
#        skipUpdateCheck: true
#        instanceId: ItemInboundInstance
#    jdbc:
#      initialize-schema: never
#  batch:
#    jdbc:
#      initialize-schema: never
#      isolation-level-for-create: default
#      schema:
#    job:
#      enabled: false

  datasource:
    properties:
      requireSecureTransport: ON
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mawmintegration?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Vardhan36Shift
    schema-initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none


jobs:
  mms_asn:
    job-name: mms_asn
    type: BATCH
    isEnabled: true
    root-directory: /upload
    drop-directory: /drop
    chunk-size: 100
    file-pattern: '*ASN-*.csv'
    maxFilesPerPoll: 3
    pollFrequencyInSecond: 5
    destination:
      dest-type: SFTP
      paths:
        mms_asn:
          path: /upload/post
      queues:
        mms_asn:
          name: INB_ImportAsn_GCPQ
          headers:
            MSG_TYPE: INB_Asn
  br_asn:
    job-name: br_asn
    type: BATCH
    isEnabled: true
    root-directory: /home/lchintala/upload
    drop-directory: /drop
    chunk-size: 100
    file-pattern: '*ASN-*.xml'
    maxFilesPerPoll: 3
    pollFrequencyInSecond: 5
    destination:
      dest-type: SFTP
      paths:
        br_asn:
          path: /upload/post
      queues:
        br_asn:
          name: INB_ImportAsn_GCPQ
          headers:
            MSG_TYPE: INB_Asn
    po:
      job-name: item
      type: BATCH
      isEnabled: true
      root-directory: /upload
      drop-directory: /drop
      chunk-size: 100
      file-pattern: '*PO-*.csv'
      maxFilesPerPoll: 3
      pollFrequencyInSecond: 5
      destination:
        dest-type: SFTP
        paths:
          po:
            path: /upload/MMMS_Po
        queues:
          mms-item:
            name: INB_ImportItem_GCPQ
            headers:
              MSG_TYPE: INB_PO

props:
  minimumLTLDeliverSize: 72
  minimumLTLTransferSize: 96
  skipItemLocationSkuStatus: I
  entityCreateEvent:
    item:
      enabled: true
      queue: EntityCreated
  infiniteSupply:
    skuTypes: PO


purge:
  sftp:
    enabled: true
    retentionDays: 60
    folderIdentifier:
      - output
  retentions:
    item: 5

mawm:
  auth:
    useBase: false
    authorization: Basic b21uaWNvbXBvbmVudC4xLjAuMDpiNHM4cmdUeWc1NVhZTnVu
    endPoint: /oauth/token
    grantType: password
    isEncrypted: false
    password:
    refreshFrequency: 1800000
    refreshRequired: false
    url:
    username:
  enabled: false
  log-level: BASIC
  orgId: FnDDevelopment-US
  retry:
    httpMaxRetryAttempts: 3
    httpRetryInterval: 1000
    retryRequired: false
  timeout:
    connection: 5000
    read: 8000
  url: